/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "cape-spear-hero": {
    "base": "cape-spear-hero",
    "width": 1920,
    "height": 1461,
    "fallbackWidth": 800,
    "fallbackHeight": 609,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "iceberg-hero": {
    "base": "iceberg-hero",
    "width": 1884,
    "height": 1918,
    "fallbackWidth": 800,
    "fallbackHeight": 814,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "jellybean-row-hero": {
    "base": "jellybean-row-hero",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "port-hero": {
    "base": "port-hero",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "puffin-hero": {
    "base": "puffin-hero",
    "width": 1920,
    "height": 1536,
    "fallbackWidth": 800,
    "fallbackHeight": 640,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "quidi-vidi-hero": {
    "base": "quidi-vidi-hero",
    "width": 1920,
    "height": 440,
    "fallbackWidth": 800,
    "fallbackHeight": 183,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "signal-hill-hero": {
    "base": "signal-hill-hero",
    "width": 1920,
    "height": 1371,
    "fallbackWidth": 800,
    "fallbackHeight": 571,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "st-johns-hero": {
    "base": "st-johns-hero",
    "width": 800,
    "height": 502,
    "fallbackWidth": 800,
    "fallbackHeight": 502,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "whale-hero": {
    "base": "whale-hero",
    "width": 1573,
    "height": 885,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
